services:
  postgres:
    image: postgres:18
    container_name: kde-cpi-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./init.d:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4:9.9
    container_name: kde-cpi-pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  duckdb:
    image: datacatering/duckdb:v1.4.1
    container_name: kde-cpi-duckdb
    stdin_open: true
    tty: true
    working_dir: /data
    volumes:
      - duckdb-data:/data
      - ./:/workspace:ro

volumes:
  postgres-data:
  pgadmin-data:
  duckdb-data:
