name: Bump Version

on:
  workflow_dispatch:
    inputs:
      part:
        description: "Which part of the version to bump"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install bump-my-version
        run: |
          python -m pip install --upgrade pip
          python -m pip install bump-my-version

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump project version
        env:
          PART: ${{ github.event.inputs.part }}
        run: |
          bump-my-version bump ${PART}
          bump-my-version show

      - name: Push changes and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main
          git push origin --tags
