name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

concurrency:
  group: release-${{ github.event.release.tag_name || github.run_id }}
  cancel-in-progress: false

env:
  PACKAGE_NAME: kde-cpi

jobs:
  build:
    name: Build sdist & wheel (from tag)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          persist-credentials: true

      # Make sure tags are present for setuptools-scm
      - name: Ensure tags are fetched
        run: git fetch --force --tags

      # Safety: ensure the tag is reachable from main (same guard you had)
      - name: Ensure tag commit is on main
        shell: bash
        run: |
          set -euo pipefail
          TAG='${{ github.event.release.tag_name }}'
          git fetch origin main
          TAG_SHA="$(git rev-list -n 1 "$TAG")"
          if ! git merge-base --is-ancestor "$TAG_SHA" origin/main; then
            echo "::error::Release tag $TAG ($TAG_SHA) is not reachable from origin/main."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build distributions
        run: python -m build # setuptools-scm reads the tag, bakes version

      - name: Twine check
        run: python -m twine check dist/*

      - name: Smoke test the wheel
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install dist/*.whl
          kde-cpi --help >/dev/null

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error
          retention-days: 7

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
          attestations: true
          print-hash: true

  publish-to-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          attestations: true
          print-hash: true
