name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write # build notes/assets if you ever add them
  id-token: write # OIDC for (Test)PyPI Trusted Publisher
  attestations: write

concurrency:
  group: release-${{ github.event.release.tag_name || github.run_id }}
  cancel-in-progress: false

env:
  PACKAGE_NAME: kde-cpi

jobs:
  build:
    name: Build sdist & wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }} # build exactly the released tag
          fetch-depth: 0
          persist-credentials: true # needed for git fetch origin main on private repos

      - name: Ensure tag commit is on main
        shell: bash
        run: |
          set -euo pipefail
          TAG='${{ github.event.release.tag_name }}'
          git fetch origin main
          TAG_SHA="$(git rev-list -n 1 "$TAG")"
          if ! git merge-base --is-ancestor "$TAG_SHA" origin/main; then
            echo "::error::Release tag $TAG ($TAG_SHA) is not reachable from origin/main."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt

      - name: Verify tag matches project version
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          TAG="${{ github.event.release.tag_name }}"
          TAG="${TAG#v}"

          PYPROJECT_VERSION="$(python - <<'PY'
          import tomllib, pathlib
          print(tomllib.loads(pathlib.Path("pyproject.toml").read_text())["project"]["version"])
          PY
          )"
              echo "file_ver=$PYPROJECT_VERSION" >> "$GITHUB_OUTPUT"
              echo "tag_ver=$TAG" >> "$GITHUB_OUTPUT"

              if [ "$TAG" != "$PYPROJECT_VERSION" ]; then
                echo "::error::Tag v$TAG != pyproject version $PYPROJECT_VERSION"
                exit 1
              fi

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build distributions
        run: python -m build

      - name: Twine check
        run: python -m twine check dist/*

      - name: Smoke test the wheel
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install dist/*.whl
          kde-cpi --help >/dev/null

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error
          retention-days: 7

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
          attestations: true
          print-hash: true

  publish-to-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          attestations: true
          print-hash: true
